### ISSUE TITLE
add-kibana operation is deploying oldest release

### ISSUE THREAD

**Issue by pdiwan** [bosh-elastic-stack/elasticsearch-boshrelease#20]
The kibana release version is hardcoded to the v0.1.0 - https://github.com/bosh-elastic-stack/elasticsearch-boshrelease/blob/master/manifest/add-kibana.yml#L10
So even with the latest elasticsearch-boshrelease, using add-kibana ops file does not guarantee latest kibana release.

**Comment by making** [comment]
Thanks for pointing it out.
I’ll delete manifests related to kibana because there are some circular dependencies between this release and kibana bosh release.

As described in README, elastic-bosh-deployment is supposed to be used
