### ISSUE TITLE
Post-Startスクリプトやerrandでbasic認証を使いたい

### ISSUE THREAD

**Issue by TakafumiShinose** [bosh-elastic-stack/elasticsearch-boshrelease#22]
Post-Startスクリプトやerrandでbasic認証を使用したいです。
下記のようにymlで認証用ユーザのパラメータを持てると望ましいです。

### jobs/elasticsearch/templates/bin/post-start 
```
curl -u $elasticsearch_user:$elasticsearch_pass -s -f --max-time $timeout -sw '\n%{http_code}' http://127.0.0.1:9200/_cluster/health > ${out}
```
### params.yml
```
---
elasticsearch_user: my_user
elasticsearch_pass: my_password
```

**Comment by making** [comment]
fixed via https://github.com/bosh-elastic-stack/elasticsearch-boshrelease/commit/99c63eda8579efb8348c9975a609ef5c97b8d4d8

**Comment by making** [comment]
See also https://github.com/bosh-elastic-stack/elastic-stack-bosh-deployment/commit/5fb76eb8c8dca1bb80fba834526ffab087fa8c43
