### ISSUE TITLE
Fix start script due to monit bug

### ISSUE THREAD

**Issue by antoniocascais** [bosh-elastic-stack/elasticsearch-boshrelease#25]
Hi.

A few days ago we had problems while deploying our cluster. What happened was:

1) We started the deployment
2) In a random VM, monit was reporting the instance as failing, so the deployment was canceled.
3) That node was successfully added to the cluster. We checked the instance and ES was running, but monit was reporting the instance as failing.

After some research, we found the issue: https://community.pivotal.io/s/article/Deployment-fails-because-monit-reports-job-as-failed

Apparently it's due to a bug on monit. And since we can't change bosh to deploy monit with a newer version, we need to fix this on the release side.

Our idea is to change the `ctl` script in order to launch ES on  a sub-shell. That way the pid file is created immediately  and we know that monit will be able to read it.

But this doesn't mean that ES is running, so we need to also change the monit script to query ES  to get a successful response: only then monit will report success.

We already are working on a PR with the fix, we just opened the issue to keep track and/or discuss it :)

**Comment by SuchiSmita-N** [comment]
We opened a PR for the above issue, If you have any questions or suggestion please let us know.
