### ISSUE TITLE
Add option to create index templates

### ISSUE THREAD

**Issue by antoniocascais** [bosh-elastic-stack/elasticsearch-boshrelease#3]
Hi!

I was having a look at this elasticsearch release and I can't find the option to create index templates.

We need to be able to create index templates in our cluster and the best way would be to have a property here in the release to just pass the index templates to.

Is it too much to ask to add that property?
Or is it another way to do this?

Thanks!
António

**Comment by making** [comment]
Would you give me an example what you want to configure and you what Elasticsearch to be?

**Comment by antoniocascais** [comment]
I want to create an index template.

For example, the logsearch release has the option to create the index templates via the properties: https://github.com/cloudfoundry-community/logsearch-boshrelease/blob/develop/jobs/elasticsearch_config/spec
(see   elasticsearch_config.templates)

In that case, one just needs to send the templates via the property and then they will be created in ES. No need to manually call the API.

**Comment by making** [comment]
@antoniocascais Could you please send a pull request?

**Comment by antoniocascais** [comment]
Hi @making 

Sure!

But since I'm very new at working with bosh deployments and bosh releases, I want to run by you my idea:
I'm thinking about doing a PUT request to the index template API in the post script, as stated here: https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-templates.html#config

And the body of the PUT request will be read from a property. What do you think?

**Comment by antoniocascais** [comment]
@making PR sent: https://github.com/bosh-elastic-stack/elasticsearch-boshrelease/pull/5

Feel free to suggest improvements or to point out changes that are not according to standards. Like I said, I'm still new in the BOSH world :)

**Comment by making** [comment]
Released 0.9.0
https://github.com/bosh-elastic-stack/elasticsearch-boshrelease/releases/tag/0.9.0
