### ISSUE TITLE
Add keys to ES keystore

### ISSUE THREAD

**Issue by antoniocascais** [bosh-elastic-stack/elasticsearch-boshrelease#9]
Hi @making !

We are trying to add snapshots into our ES cluster and for that we want to have a GCP bucket to store them.

We were looking into the documentation (https://www.elastic.co/guide/en/elasticsearch/plugins/master/repository-gcs-usage.html) and it says that we need to add the google service account JSON into ES keystore.

According to the docs (https://www.elastic.co/guide/en/elasticsearch/reference/master/secure-settings.html) we need to use the `elasticsearch-keystore` lib to create the keystore and also to add keys into it.

Last Friday I was trying to open a PR to add this feature, but I struggled with the proper way to do it. One of my problems was permissions: if I SSH into an ES instance and go into the dir where the ES libs are, I see `-rwxr-xr-x 1 root root  121 Dec 17 21:15 elasticsearch-keystore`

So I couldn't run this lib as `vcap` user. I was trying to change both the `ctl` and `post-start` scripts, but I always had problems with permissions (as in, no permission to write the keystore file).

Do you have any suggestion about the best way to do this?

I'm happy to open a PR, but need a bit of help here :)

Thanks!

**Comment by making** [comment]
How about `chown -R vcap:vcap` in a script ?

**Comment by antoniocascais** [comment]
On the `elasticsearch-keystore`?

I'll try that, let's  see how it goes...

Thanks for the suggestion! :)
